name: Push data to Algolia index
on: [push, workflow_dispatch]
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Index
        run: ./gradlew runIndex
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
